apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: stt-worker-kafka-trigger-auth
spec:
  secretTargetRef:
    - parameter: password
      name: stt-worker         # Strimzi-generated secret name = KafkaUser name
      key: password
