apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags: [gitops, helm, argocd]
  annotations:
    github.com/project-slug: filipurminsky/${{ values.name }}
    argocd/app-name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: platform-core
