apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../../base/stt-worker

labels:
  - pairs:
      app.kubernetes.io/part-of: platform-core
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

patches:
  - path: patch-dev.yaml
    target:
      kind: Deployment
      name: stt-worker

replicas:
  - name: stt-worker
    count: 0

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: stt-worker
    newTag: latest
