apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../../base/worker-service

labels:
  - pairs:
      app.kubernetes.io/part-of: platform-core
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

patches:
  - path: patch-worker-resources.yaml
    target:
      kind: Deployment
      name: worker-service

replicas:
  - name: worker-service
    count: 0

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=prod
      - LOG_LEVEL=info
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: worker-service
    newName: 123456789.dkr.ecr.eu-west-1.amazonaws.com/platform-core/worker-service
    newTag: latest
