apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base
  - mock-vllm.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: platform-core
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: llm-gateway
  - path: patch-upstream.yaml
    target:
      kind: Deployment
      name: llm-gateway

replicas:
  - name: llm-gateway
    count: 1

images:
  - name: llm-gateway
    newTag: latest
