apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: worker-service
  description: Kafka consumer that processes jobs from the `jobs` topic; scales to zero via KEDA consumer-lag trigger
  annotations:
    github.com/project-slug: filipurminsky/platform-core
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - kafka
    - keda
    - demo
  links:
    - url: https://github.com/filipurminsky/platform-core/tree/main/services/worker-service
      title: Source
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: group:platform-team
  system: platform-core
  consumesApis:
    - kafka-jobs-topic
