apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-inference
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-apps
  source:
    repoURL: https://github.com/filipurminsky/platform-core.git
    targetRevision: main
    path: kustomize/overlays/dev/vllm-inference    # change to overlays/prod/vllm-inference for production
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
