apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-apps
  source:
    repoURL: https://github.com/filipurminsky/platform-core.git
    targetRevision: main
    path: kustomize/overlays/dev/worker-service    # change to overlays/prod/worker-service for production
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
