"""Prometheus metric definitions (contract §7), exposed on :9090/metrics."""

from prometheus_client import Counter, Histogram

LLM_JOBS = Counter(
    "llm_jobs_total",
    "LLM summarisation jobs by outcome",
    ["status"],  # success | error | dlq
)
LLM_TOKENS = Counter(
    "llm_tokens_generated_total",
    "Completion tokens generated by the LLM gateway",
)
LLM_REQUEST_DURATION = Histogram(
    "llm_request_duration_seconds",
    "Latency of POST /v1/chat/completions to the LLM gateway",
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0],
)
PIPELINE_FAILED = Counter(
    "pipeline_jobs_failed_total",
    "Jobs dead-lettered by stage",
    ["stage"],
)
