apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service
  labels:
    app: worker-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: worker-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
